export const SET_CURRENT_ANSWER = "SET_CURRENT_ANSWER";
export const SET_TEST = "SET_TEST";
export const SET_OPTIONS = "SET_OPTIONS";
export const SET_CURRENT_INDEX = "SET_CURRENT_INDEX";
export const SET_SHOW_RESULTS = "SET_SHOW_RESULTS";
export const SET_ANSWERS = "SET_ANSWERS";
export const SET_IS_CLICKED = "SET_IS_CLICKED";
